version: "3"

services:
  mongodb:
    image: docker.arvancloud.ir/mongo:latest
    container_name: mongodb
    ports:
      - 27011:27017

  influx:
    image: docker.arvancloud.ir/influxdb:2.7.0
    container_name: influxdb
    ports:
      - 8086:8086

  redis:
    image: docker.arvancloud.ir/redis:latest
    container_name: redis
    ports:
      - 6379:6379

  nats:
    image: docker.arvancloud.ir/nats:latest
    container_name: nats
    command: -js
    ports:
      - 8222:8222
      - 4222:4222
