version: "3"

services:
  influx:
    image: influxdb:latest
    container_name: influxdb

    ports:
      - 8086:8086

  redis:
    image: redis:latest
    container_name: redis

    ports:
      - 6379:6379
