version: "3"

services:
  influx:
    image: docker.arvancloud.ir/influxdb:latest
    container_name: influxdb

    ports:
      - 8086:8086

  redis:
    image: docker.arvancloud.ir/redis:latest
    container_name: redis

    ports:
      - 6379:6379
